# Additional maintainer keys to trust before building any packages
additional_trusted_keys = []

[image]
name = "ghcr.io/mwcaisse/aur-builder"
tag = "latest"

[repository]
# The name of the repository
name = ""
# The path to where the repository exists on disc
path = ""

[signing]
# Whether to sign packages
enabled = false
# Path to the private key to use for signing packages, required if signing is enabled
# key_path = ""
# Path to the public key to use for signing packages, required if signing is enabled
# public_key_path = ""
