name: Build Package
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_package:
    name: Build Package
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Update and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel sudo git cargo

      - name: Checkout main
        uses: actions/checkout@v5

      - name: Create build user
        run: |
          useradd -m build
          echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/build
          chmod 0440 /etc/sudoers.d/build
          chown -R build:build .

      - name: Build package
        run: sudo -u build makepkg -s --skipinteg

