name: Integration Tests
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_publish:
    name: Integration Tests
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install git
        shell: bash
        run: |
          pacman -Syyu --noconfirm
          pacman -S --noconfirm git

      - name: Checkout main
        uses: actions/checkout@v5

      - name: Install system dependencies
        uses: ./.github/actions/install-system-dependencies
        with:
          distro: arch

      - name: Build and install aur-utils
        uses: ./.github/actions/install-aur-utils

      - name: Output version of rust being used
        run: rustup --version

      - name: Install and configure docker
        shell: bash
        run: |
          pacman -S docker --noconfirm
          
          docker info

      - name: Run integration tests
        run: cargo test --test '*'